from __future__ import annotations

from typing import Annotated

from fastapi import APIRouter, Depends, Request, Response, status
from prometheus_client import CONTENT_TYPE_LATEST, CollectorRegistry, generate_latest

from app.core.dependencies import (
    get_metrics_registry,
    verify_metrics_access,
)

router = APIRouter(
    tags=["Metrics"],
)

MetricsRegistryDependency = Annotated[
    CollectorRegistry,
    Depends(get_metrics_registry),
]

MetricsAccessDependency = Annotated[
    None,
    Depends(verify_metrics_access),
]


@router.get(
    "/metrics",
    status_code=status.HTTP_200_OK,
    summary="Expose Prometheus metrics",
    include_in_schema=False,
)
async def metrics(
    request: Request,
    registry: MetricsRegistryDependency,
    _: MetricsAccessDependency,
) -> Response:
    """
    Expose API Gateway metrics in Prometheus text exposition format.

    Access should normally be restricted through one or more of:

    - private Kubernetes networking;
    - NetworkPolicy;
    - service mesh authorization;
    - internal API key;
    - trusted source IP validation.

    Do not expose this endpoint publicly without access controls.
    """
    metric_output = generate_latest(registry)

    return Response(
        content=metric_output,
        media_type=CONTENT_TYPE_LATEST,
        headers={
            "Cache-Control": "no-store",
            "X-Content-Type-Options": "nosniff",
            "X-Request-ID": _get_request_id(request) or "",
        },
    )


def _get_request_id(request: Request) -> str | None:
    """
    Return the request ID generated by request-ID middleware.
    """
    return getattr(request.state, "request_id", None)
